
# name, industry, sector, headquarters, founded, notes

germany_companies = [
'A. Lange & Söhne', 'Consumer goods',' 	Clothing & accessories','Glashütte',1845, 'Watches',
'Aareal Bank','Financials','Banks','Wiesbaden',1922,'Banking and financial services',
'Adidas','Consumer goods','Footwear','Herzogenaurach',1924,'Shoes, apparel and accessories',
'AEG','Industrials','Electronic equipment','Frankfurt',1883, 'Defunct 1996 - now part of Electrolux',
'Air Berlin','Consumer services','Airlines','Berlin', 1979,'Airline, defunct 2017',
'Aldi','Consumer services','Food retailers & wholesalers','Essen',1913,'Discount retail chains',
'Allianz','Financials','Full line insurance','Munich',1890,'Insurance and asset management',
'Alpina','Consumer goods','Automobiles','Buchloe',1965,'Automotive manufacturer',
'Altana','Basic materials','Speciality chemicals','Wesel',1977, 'Chemicals',
'Aral AG','Consumer services','Specialty retailers','Bochum',1898,'Part of BP',
'Arburg','Industrials','Industrial machinery','Loßburg',1923,'Machinery and injection molding',
'Arcandor','Consumer services','Broadline retailers','Essen',1999,'Defunct 2009',
'Arcor','Telecommunications','Fixed line telecommunications','Eschborn',1966,'Telecom, part of Vodafone (UK)',
'Armedangels','Consumer goods','Clothing & accessories','Cologne',2007,'Fashion',
'Audi','Consumer goods','Automobiles','Ingolstadt',1910,'Auto manufacturer, part of Volkswagen Group',
'August Storck','Consumer goods','Food products','Berlin',1903,'Confectionery',
'Aurubis','Basic materials','Nonferrous metals','Hamburg',2008,'Copper manufacturing',
'Auto Union','Consumer goods','Automobiles','Neckarsulm',1932,'Defunct, now part of Audi',
'Axel Springer AG','Consumer services','Publishing','Berlin',1946,'Digital publishing',
'Babelsberg Studio','Consumer services','Broadcasting & entertainment','Potsdam',1912,'Film studio',
'Bahlsen','Consumer goods','Food products','Hanover',1889,'Biscuits and cakes',
'BASF','Basic materials','Speciality chemicals','Ludwigshafen',1865,'Largest chemical producer in the world',
'Bavaria Film Studios','Consumer services','Broadcasting & entertainment','Grünwald',1919,'Film studio',
'Bayer','Health care','Pharmaceuticals','Leverkusen',1863,'Chemicals and pharmaceuticals',
'BayWa','Consumer goods','Farming & fishing','Munich',1923,'Agribusiness conglomerate',
'BBS Kraftfahrzeugtechnik','Consumer goods','Auto parts','Schiltach',1970,'Automotive parts',
'Bechtle','Technology','Software','Neckarsulm',1983,'Information technology services',
'Beck\'s Brewery','Consumer goods','Brewers','Bremen',1873,'Alcoholic beverages',
'Behr GmbH & Co. KG','Industrials','Industrial suppliers','Stuttgart',1905,'Part of Mahle GmbH',
'Behringer','Consumer goods','Consumer electronics','Willich',1989,'Audio systems',
'Beiersdorf','Consumer goods','Personal products','Hamburg',1882,'Cosmetics',
'Bellevue Investments','Technology','Software','Berlin',1993,'Software holding company',
'Benecke-Kaliko','Industrials','Industrial suppliers','Hanover',1718,'Automotive parts',
'Bertelsmann','Consumer services','Broadcasting & entertainment','Gütersloh',1835,'Mass media',
'Beyerdynamic','Consumer goods','Consumer electronics','Heilbronn',1924,'Audio electronics',
'Bilfinger','Industrials','Heavy construction','Mannheim',1880,'Construction, engineering and services',
'Birkenstock','Consumer goods','Footwear','Neustadt',1774,'Shoe manufacturer',
'Bitburger Brewery','Consumer goods','Brewers','Bitburg',1817,'Brewery',
'Blaupunkt','Consumer goods','Consumer electronics','Hildesheim',1923,'Home and car audio, defunct 2016',
'Blohm+Voss','Industrials','Commercial vehicles & trucks','Hamburg',1877,'Shipyard, part of Lürssen',
'BMG Rights Management','Consumer services','Broadcasting & entertainment','Berlin',2008,'Music, part of Bertelsmann',
'BMW','Consumer goods','Automobiles','Munich',1916,'Automotive',
'Bodan-Werft','Industrials','Commercial vehicles & trucks','Kressbronn am Bodensee',1919,'Defunct 2011, now independent firms for pools and a yacht harbour',
'Boehringer Ingelheim','Health care','Pharmaceuticals','Ingelheim am Rhein',1885,'Pharmaceuticals',
'BOMAG','Industrials','Commercial vehicles & trucks','Boppard',1957,'Mechanical engineering',
'Brabus','Consumer services','Specialty retailers','Bottrop',1977,'Automotive modifications and tuning',
'Braun','Consumer goods','Personal products','Kronberg',1921,'Razors and small appliances, part of Procter & Gamble (US)',
'Bremer Vulkan','Industrials','Commercial vehicles & trucks','Bremen-Vegesack',1893,'Shipyard, defunct 1997',
'Brenntag','Basic materials','Commodity chemicals','Mülheim',1874,'Chemical distribution',
'Büssing AG','Industrials','Commercial vehicles & trucks','Braunschweig',1903,'Bus and truck, defunct 1971, now part of MAN',
'C. Bechstein','Consumer goods','Recreational products','Berlin',1853,'Musical instruments',
'C. Illies & Co.','Industrials','Business support services','Hamburg',1859,'Engineering and export',
'Carl Walther GmbH','Industrials','Defense','Ulm',1886,'Firearms',
'Carl Zeiss AG','Health care','Medical equipment','Oberkochen',1846,'Optical systems, part of Carl-Zeiss-Stiftung',
'Carl-Zeiss-Stiftung','Health care','Medical equipment','Heidenheim an der Brenz',1889,'Holding company',
'Celesio','Health care','Pharmaceuticals','Stuttgart',1835,'Pharmaceuticals, defunct 2017, now part of McKesson',
'Circus Krone','Consumer services','Broadcasting & entertainment','Munich',1905,'Circus, entertainment',
'Claas','Industrials','Commercial vehicles & trucks','Harsewinkel',1913,'Agricultural machinery',
'Commerzbank','Financials','Banks','Frankfurt',1870,'Banking',
'Condor Flugdienst','Consumer services','Airlines','Frankfurt',1955,'Leisure airline, part of Thomas Cook Group (UK)',
'Continental AG','Industrials','Industrial suppliers','Hanover',1871,'Auto parts and supplies, part of Schaeffler Group',
'Covestro','Basic materials','Speciality chemicals','Leverkusen',2015,'Materials and coatings, part of Bayer',
'Daimler AG','Consumer goods','Automobiles','Stuttgart',2007,'Multinational automotive firm',
'Dba','Consumer services','Airlines','Munich',1992,'Low-cost airline, defunct 2008',
'Delton','Conglomerates','-','Bad Homburg vor der Höhe',1989,'Pharma, consumer goods, logistics',
'Der Spiegel','Consumer services','Publishing','Hamburg',1947,'Weekly news magazine',
'Deutsche Bahn','Industrials','Railroads','Berlin',1994,'State railways',
'Deutsche Bank','Financials','Banks','Frankfurt',1870,'Banking',
'Deutsche Börse','Financials','Investment services','Frankfurt',1992,'Securities marketplace',
'Deutsche Grammophon','Consumer goods','Broadcasting & entertainment','Hanover',1898,'Phonogramm producer, producer of the first Compact disc, now part of Universal Music Group (US)',
'Deutsche Messe','Consumer services','Recreational services','Hanover',1947,'Largest fairground in the world',
'Deutsche Pfandbriefbank','Financials','Banks','Unterschleißheim',2015,'Real estate financing bank',
'Deutsche Post','Industrials','Delivery services','Bonn',1995,'Postal services',
'Deutsche Telekom','Telecommunications','Fixed line telecommunications','Bonn',1995,'Telecommunications',
'Deutsche Vermögensberatung','Financials','Asset managers','Frankfurt',1975,'Financial advice',
'Deutz AG','Industrials','Industrial machinery','Cologne',1864,'Mechanical engineering',
'DHL Express','Industrials','Delivery services','Bonn',1969,'Logistics, part of Deutsche Post',
'Dieffenbacher','Industrials','Industrial machinery','Eppingen',1873,'Machinery',
'Diehl Aerospace','Industrials','Aerospace','Überlingen',2006,'Avionics',
'Diehl Defence','Industrials','Defense','Überlingen',2004,'Arms',
'Diehl Metall','Industrials','Industrial machinery','Röthenbach an der Pegnitz',1938,'Metals, forges',
'Diezel','Consumer goods','Recreational products','Bad Steben',1994,'Guitar amplifiers',
'Djshop','Consumer services','Broadcasting & entertainment','Vachendorf',1993,'Online dance music retail store',
'Dornier Flugzeugwerke','Industrials','Aerospace','Friedrichshafen',1922,'Aircraft manufacturer, defunct 2002',
'Douglas Holding','Consumer services','Specialty retailers','Hagen',1949,'Perfume and cosmetics retailer',
'DOVO Solingen','Consumer goods','Personal products','Solingen',1906,'Scissors and razors',
'Dr. Oetker','Consumer goods','Food products','Bielefeld',1891,'Food producer',
'Dräger','Health care','Medical equipment','Lübeck',1889,'Medical technology',
'Dresdner Bank','Financials','Banks','Frankfurt',1872,'Now part of Commerzbank, defunct 2009',
'Dürr AG','Industrials','Industrial machinery','Stuttgart',1895,'Plant and machinery construction',
'DVB Bank','Financials','Banks','Frankfurt',1923,'Financials',
'E.ON','Utilities','Electricity','Essen',2000,'Electric power',
'Eberhard Faber','Consumer goods','Nondurable household products','Neumarkt in der Oberpfalz',1922,'Part of Staedtler',
'ebm-papst','Industrials','Industrial machinery','Mulfingen',1963,'Electric motors and fans',
'edding','Consumer goods','Nondurable household products','Ahrensburg',1960,'Writing instruments',
'Edeka','Consumer services','Food retailers & wholesalers','Berlin',1898,'Supermarkets',
'ElringKlinger','Industrials','Industrial suppliers','Dettingen an der Erms',1879,'Automotive parts',
'EnBW','Utilities','Electricity','Karlsruhe',1997,'Electric power',
'EnOcean','Consumer goods','Consumer electronics','Oberhaching',2001,'Electronics',
'Entwicklungsring Nord','Industrials','Aerospace','Bremen',1961,'Rocket parts, defunct 1977',
'Epcos','Consumer goods','Consumer electronics','Munich',1999,'Electronics',
'E-Plus','Telecommunications','Mobile telecommunications','Düsseldorf',1992,'Mobile network, part of Telefónica Germany',
'Evonik Industries','Basic materials','Speciality chemicals','Essen',2007,'Specialty chemicals',
'Faber-Castell','Consumer goods','Nondurable household products','Stein',1761,'Writing instruments',
'Fein','Consumer goods','Durable household products','Schwäbisch Gmünd',1867,'Power tools',
'Ferrostaal','Industrials','Industrial machinery','Essen',1920,'Industrial services, machinery',
'Festo','Industrials','Industrial machinery','Esslingen am Neckar',1925,'Automation',
'Fischertechnik','Consumer goods','Toys','Waldachtal',1966,'Construction sets',
'Fissler','Consumer goods','Durable household products','Idar-Oberstein',1845,'ookware manufacturer',
'Focke-Achgelis','Industrials','Aerospace','Hoykenkamp',1937,'Defunct helicopter manufacturer',
'Focke-Wulf','Industrials','Aerospace','Bremen',1923,'Aircraft manufacturer, defunct 1964',
'Fond of Bags','Consumer goods','Clothing & accessories','Cologne',2010,'Backpacks',
'Ford Germany','Consumer goods','Automobiles','Cologne',1925,' 	Automobile manufacturer, part of Ford Motor Company (US)',
'Ford of Europe','Consumer goods','Automobiles','Cologne',1967,'Automobile manufacturer, part of Ford Motor Company (US)',
'Franz Haniel & Cie.','Conglomerates','-','Duisburg',1756,'Family holding company',
'Fraport','Industrials','Transportation services','Frankfurt',1924,'Airports',
'Freenet.de','Telecommunications','Fixed line telecommunications','Büdelsdorf',2007,'Telecommunications',
'Fresenius','Health care','Health care providers','Bad Homburg vor der Höhe',1912,'Health care',
'Fresenius Medical Care','Health care','Health care providers','Bad Homburg vor der Höhe',1996,'Part of Fresenius',
'Freudenberg Group','Conglomerates','-','Weinheim',1849,'Consumer goods, telecommunications, industrials',
'FRoSTA','Consumer goods','Food products','Bremerhaven',1905,'Frozen foods, foodservice, commercial catering',
'Fuchs Petrolub','Basic materials','Speciality chemicals','Mannheim',1931,'Lubricants',
'Gardena','Consumer goods','Durable household products','Ulm',1961,'Garden tools',
'GEA Group','Industrials','Industrial machinery','Düsseldorf',1881,'Machinery and technology for refrigeration and livestock farming',
'Gebrüder Thonet','Consumer goods','Furnishings','Frankenberg',1853,'Furniture manufacturer',
'Gerolsteiner Brunnen','Consumer goods','Beverages','Gerolstein',1888,'Mineral water',
'Gerresheimer','Industrials','Containers & packaging','Düsseldorf',1864,'Packaging products',
'Getrag','ndustrials','Industrial suppliers','Untergruppenbach',1935,'Automotive parts',
'GfK AG','Industrials','Business support services','Nuremberg',1934,'Market research',
'GPC Biotech','Health care','Biotechnology','Martinsried',1997,'Biotechnology',
'Grundig','Consumer goods','Consumer electronics','Nuremberg',1930,'Electronics, part of Koç Holding (Turkey)',
'Gruner + Jahr','Consumer services','Publishing','Hamburg',1965,'Publishing house, part of Bertelsmann',
'Hama Photo','Consumer goods','Consumer electronics','Monheim',1923,'Electronics',
'Hamburg Süd','Industrials','Marine transportation','Hamburg',1871,'Shipping',
'Hamburger Flugzeugbau','Industrials','Aerospace','Hamburg',1933,'Aircraft manufacturer, defunct 1969',
'Hannover Re','Financials','Reinsurance','Hanover',1966,'Reinsurance firm',
'Hapag-Lloyd','Industrials','Marine transportation','Hamburg',1970,'Shipping',
'Haribo','Consumer goods','Food products','Bonn',1920,'Confectionery'
'Heckler & Koch','Industrials','Defense','Oberndorf am Neckar',1948,'Arms',
'HeidelbergCement','Industrials','Building materials & fixtures','Heidelberg',1874,'Building materials',
'Heidelberger Druckmaschinen','Industrials','Industrial machinery','Heidelberg',1850,'Printing machines',
'Heinkel','Industrials','Aerospace','Warnemünde',1922,'Aircraft manufacturer, defunct 1965',
'Hella','Industrials','Industrial suppliers','Lippstadt',1899,'Automotive parts',
'Henkel','Conglomerates','-','Düsseldorf',1876,'Consumer goods, industrial goods',
'Heraeus','Industrials','Industrial machinery','Hanau',1851,'Engineering',
'Herrenknecht','Industrials','Industrial machinery','Schwanau',1975,'Tunnel boring machines',
'Hochtief','Industrials','Heavy construction','Essen',1874,'Construction',
'Hoechst','Basic materials','Specialty chemicals','Frankfurt',1863,'Chemicals, defunct 2004',
'Hoesch','Mining','-','Dortmund',1871,'Minig, steel, defunct 1991',
'Horváth & Partners','Industrials','Business support services','Stuttgart',1981,'Management consulting',
'Howaldtswerke-Deutsche Werft','Industrials','Commercial vehicles & trucks','Kiel',1838,'Shipbuilding',
'Hubert Burda Media','Consumer services','Publishing','Offenburg',1903,'Publishing and mass media',
'Hugo Boss','Consumer goods','Clothing & accessories','Metzingen',1924,'Luxury fashion',
'HypoVereinsbank','Financials','Financial services','Munich',1998,'Finance and insurance, part of UniCredit (Italy)',
'Hypo Real Estate','Financials','Real estate','Munich',2003,'Nationalized holding company',
'IAV','Industrials','Industrial suppliers','Berlin',1983,'Automotive supplier',
'IG Farben','Basic materials','Commodity chemicals','Frankfurt',1925,'Defunct 2012',
'Infineon Technologies','Technology','Semiconductors','Neubiberg',1999,'Semiconductor manufacturer',
'Intershop','Consumer services','Specialty retailers','Berlin',1962,'Defunct 1990',
'J. A. Henckels','Consumer goods','Durable household products','Solingen',1731,'Kitchenware',
'J. Schmalz','Industrials','Industrial machinery','Glatten',1910,'Vacuum technology',
'Jack Wolfskin','Consumer goods','Recreational products','Idstein',1981,'Camping and outdoor',
'Jenoptik','Industrials','Industrial machinery','Jena',1991,'Optoelectronics engineering',
'Jil Sander','Consumer goods','Clothing & accessories','Hamburg',1968,'Fashion',
'Junghans','Consumer goods','Clothing & accessories','Schramberg',1861,'Watches',
'Junkers','Industrials','Aerospace','Dessau',1895,'Aircraft manufacturer, defunct 1969',
'K+S','Basic materials','Speciality chemicals','Kassel',1889,'Fertilisers',
'Kärcher','Industrials','Waste & disposal services','Winnenden',1935,'Cleaning equipment',
'Kaufland','Consumer services','Food retailers & wholesalers','Neckarsulm',1985,'Hypermarket, part of Schwarz Gruppe',
'Keimfarben','Basic materials','Speciality chemicals','Diedorf',1878,'Paints',
'KfW','Financials','Banks','Frankfurt',1906,'Financial services',
'Klöckner & Co SE','Industrials','Industrial machinery','Duisburg',1906,'Metal distribution',
'Knorr','Consumer goods','Food products','Heilbronn',1838,'Food brand, part of Unilever (Netherlands)',
'Knorr-Bremse','Industrials','Industrial suppliers','Munich',1905,'Braking systems',
'Koenig & Bauer','Industrials','Industrial machinery','Würzburg',1817,'Printing machines',
'Körber','Industrials','Industrial machinery','Hamburg',1995,'Mechanical engineering',
'Krauss-Maffei','Industrials','Industrial machinery','Munich',1931,'Mechanical engineering, part of ChemChina (China)',
'Krones','Industrials','Industrial machinery','Neutraubling',1951,'Mechanical engineering',
'KSB Company','Industrials','Industrial machinery','Frankenthal',1871,'Mechanical engineering',
'KUKA','Industrials','Industrial machinery','Augsburg',1898,'Automation',
'Lamy','Consumer goods','Nondurable household products','Heidelberg',1930,'Writing instruments',
'Lanxess','Basic materials','Speciality chemicals','Cologne',2004,'Chemicals',
'Leica Camera','Consumer goods','Recreational products','Wetzlar','1914','Optical imaging',
'Leidolf','Consumer goods','Recreational products','Wetzlar',1921,'Cameras, defunct 1962',
'Leoni AG','Industrials','Electrical components & equipment','Nuremberg',1917,'Cable and harnessing manufacturing',
'Lidl','Consumer services','Food retailers & wholesalers','Neckarsulm',1930,'Part of Schwarz Gruppe',
'Lindauer Dornier','Consumer goods','Clothing & accessories','Lindau',1985,'Textile machinery',
'Linguatec','Technology','Software','Pasing',1996,'Machine translation',
'Linhof','Consumer goods','Recreational products','Munich',1887,'Camera manufacturer',
'Loewe','Consumer goods','Consumer electronics','Kronach',1923,'Consumer electronics',
'Löwenbräu','Consumer goods','Brewers','Munich',1383,'Brewery, part of Anheuser-Busch InBev (Belgium)',
'LSG Sky Chefs','Industrials','Transportation services','Neu-Isenburg',1942,'Airline catering, part of Lufthansa',
'LTU International','Consumer services','Airlines','Düsseldorf',1955,'Leisure airline, defunct 2009',
'Lufthansa','Consumer services','Airlines','Cologne',1955,'Largest German airline',
'Lürssen','Industrials','Commercial vehicles & trucks','Bremen-Vegesack',1875,'Shipyard',
'Magirus','Industrials','Commercial vehicles & trucks','Ulm',1866,'Trucks and industrial vehicles',
'Magix','Technology','Software','Berlin',1994,'Software publisher, part of Bellevue Investments',
'Mahle GmbH','Industrials','Industrial suppliers','Stuttgart',1920,'Automotive parts',
'MAN','Industrials','Commercial Vehicles & Trucks','Munich',1758,'Automotive, mechanical engineering, part of Volkswagen Group',
'Mann+Hummel','Industrials','Industrial suppliers','Ludwigsburg',1941,'Automotive parts',
'Mannesmann','Industrials','Diversified industrials','Düsseldorf',1890,'Now part of Vodafone, ThyssenKrupp, Siemens, Salzgitter AG',
'Mast-Jägermeister','Consumer goods','Distillers & vintners','Wolfenbüttel',1878,'Alcohol',
'Meindl','Consumer goods','Footwear','Kirchanschöring',1683,'Shoe manufacturer',
'Meinl Percussion','Consumer goods','Recreational products','Gutenstetten',1951,'Musical instruments',
'Meinl-Weston','Consumer goods','Recreational products','Geretsried',1810,'Musical instruments',
'Meissen porcelain','Consumer goods','Durable household products','Meissen',1708,'Porcelain',
'Melitta','Consumer goods','Beverages','Minden',1908,'Coffee',
'Mennekes','Industrials','Electrical components & equipment','Kirchhundem',1935,'Industrial plugs and connectors',
'Mercedes-AMG','Consumer goods','Automobiles','Affalterbach',1967,'Automobile and engine manufacturing, part of Daimler AG',
'Mercedes-Benz','Consumer goods','Automobiles','Stuttgart',1883,'Automotive, part of Daimler AG',
'Merck','Health care','Pharmaceuticals','Darmstadt',1668,'Pharmaceuticals',
'Messerschmitt','Industrials','Aerospace','Augsburg',1938,'Aircraft manufacturer, defunct 1968',
'Metro AG','Consumer services','Broadline retailers','Düsseldorf',1964,'Diversified retailer',
'Metz','Consumer goods','Consumer electronics','Zirndorf',1938,'Electronics manufacturer, defunct 2014',
'Meyer Werft','Industrials','Commercial vehicles & trucks','Papenburg',1795,'Shipbuilding',
'Miele','Consumer goods','Durable household products','Gütersloh',1899,'Domestic appliances',
'Montblanc','Consumer goods','Nondurable household products','Hamburg',1906,'Luxury goods',
'Munich Re','Financials','Reinsurance','Munich',1880,'Reinsurance',
'Nemetschek','Technology','Software','Munich',1963,'Software',
'Nero AG','Technology','Software','Karlsruhe',1995,'Software',
'Netto Marken-Discount','Consumer services','Food retailers & wholesalers','Maxhütte-Haidhof',1984,'Supermarkets, part of Edeka',
'Nordzucker','Consumer goods','Food products','Braunschweig',1997,'Sugar',
'NSU Motorenwerke','Consumer goods','Automobiles','Neckarsulm',1873,'Now part of Audi, defunct',
'Opel','Consumer goods','Automobiles','Rüsselsheim am Main',1862,'Automotive, part of Groupe PSA (France)',
'Orenstein & Koppel','Industrials','Industrial vehicles & trucks','Berlin',1876,'Defunct 1999',
'Osram','Industrials','Building materials & fixtures','Munich',1919,'Lighting',
'Otto GmbH','Consumer services','Broadline retailers','Hamburg',1949,'Mail order company',
'Otto Bock','Health care','Medical equipment','Duderstadt',1919,'Wheel chairs, prosthetics',
'Paulaner Brewery','Consumer goods','Brewers','Munich',1634,'Brewery, part of Brau Holding International',
'PCC SE','Basic materials','Speciality chemicals','Duisburg',1993,'Chemicals, energy, logistics',
'Penny','Consumer services','Food retailers & wholesalers','Cologne',1973,'Supermarkets, part of REWE Group',
'Philipp Holzmann','Industrials','Heavy construction','Frankfurt',1849,'Defunct 2002',
'Phoenix Contact','Industrials','Industrial machinery','Blomberg',1923,'Automation',
'Plus','Consumer services','Food retailers & wholesalers','Mülheim',1972,'Part of Edeka, defunct 2009',
'Porsche','Consumer goods','Automobiles','Stuttgart',1931,'High performance vehicles, part of Volkswagen Group',
'ProSiebenSat.1','Consumer services','Broadcasting & entertainment','Unterföhring',2000,'Mass media',
'PTV AG','Technology','Software','Karlsruhe',1979,'Software design and consulting',
'PUMA','Consumer goods','Clothing & accessories','Herzogenaurach',1948,'Apparel and accessories',
'Putzmeister','Industrials','Industrial machinery','Aichtal',1958,'Concrete pumps',
'Radeberger Brewery','Consumer goods','Brewers','Radeberg',1872,'Brewery, part of Dr. Oetker',
'Recaro','Industrials','Industrial suppliers','Stuttgart',1906,'Vehicle seating',
'Reemtsma','Consumer goods','Tobacco','Hamburg',1910,'Tobacco and cigarette',
'REWE Group','Consumer services','Food retailers & wholesalers','Cologne',1927,'Supermarkets, retail',
'Rheinmetall','Industrials','Defense','Düsseldorf',1889,'Defense and automotive',
'Rheinmetall Automotive','Industrials','Industrial suppliers','Neckarsulm',1997,'Automotive parts, part of Rheinmetall',
'Rimowa','Consumer goods','Luggage','Cologne',1898,'Luggage and travel accessories, acquired by LVMH in 2016',
'Ritter Sport','Consumer goods','Food products','Waldenbuch',1912,'Chocolates',
'Robert Bosch GmbH','Consumer goods','Durable household products','Waldenbuch',1886,'Automotive parts, home appliance',
'Rohde & Schwarz','Industrials','Electronic equipment','Munich',1933,'Electronics',
'ROSE Bikes','Consumer goods','Recreational products','Bocholt',1907,'Bicycles',
'RRI Rhein Ruhr International','Industrials','Industrial machinery','Essen',1942,'Engineering',
'RUF Automobile','Consumer goods','Automobiles','Pfaffenhausen',1939,'Automotive',
'RWE','Utilities','Electricity','Essen',1898,'Electric generation and distribution',
'SABA','Consumer goods','Consumer electronics','Triberg im Schwarzwald',1923,'Radios, defunct 1980',
'Salzgitter AG','Basic materials','Iron & steel','Salzgitter',1937,'Steel producer',
'SAP SE','Technology','Software','Walldorf',1972,'Enterprise software',
'Sauer Flugmotorenbau','Industrials','Aerospace','Ober-Olm',None,'Aviation engines',
'Schaeffler Group','Industrials','Industrial suppliers','Herzogenaurach',1883,'Automotive parts',
'Schaffhausen Communication Group','Industrials','Business support services','Elmshorn',1978,'Advertising',
'Schaller Guitarenparts','Consumer goods','Recreational products','Postbauer-Heng',1945,'Musical instruments',
'Schering','Health care','Pharmaceuticals','Berlin',1851,'Defunct 2006, now part of Bayer',
'Schmitz Cargobull','Industrials','Commercial Vehicles & Trucks','Horstmar',1892,'Trailers and truck bodies',
'Schott AG','Basic materials','Speciality chemicals','Mainz',1884,'Industrial glass, part of Carl-Zeiss-Stiftung',
'Schwan-Stabilo','Consumer goods','Nondurable household products','Heroldsberg',1855,'Writing instruments',
'Schwarz Gruppe','Consumer services','Food retailers & wholesalers','Neckarsulm',1973,'Supermarket holding company',
'Schwind eye-tech-solutions','Health care','Medical equipment','Kleinostheim',1958,'Medical technology',
'Sebamed','Consumer goods','Personal products','Boppard',1957,'Skin care products',
'Seca','Health care','Medical equipment','Hamburg',1840,'Medical scales and measuring instruments',
'Sennheiser','Consumer goods','Consumer electronics','Wedemark',1945,'Audio electronics',
'Severin Elektro','Consumer goods','Durable household products','Sundern',1892,'Household appliances',
'SEW Eurodrive','Industrials','General industrials','Bruchsal',1931,'Electric motors',
'SGL Carbon','Basic materials','Chemicals','Wiesbaden',1992,'Chemicals',
'Siemens','Conglomerates','-','Berlin',1847,'Industrials, energy, health care',
'SIG Sauer','Industrials','Defense','Eckernförde',1976,'Firearms',
'SimScale','Technology','Software','Munich',2012,'Engineering simulation software',
'SkySails','Industrials','Industrial machinery','Hamburg',2001,'Marine propulsion by wind energy',
'Smart','Consumer goods','Automobiles','Böblingen',1994,'Automotive, part of Daimler AG',
'Software AG','Technology','Software','Darmstadt',1969,'Enterprise software',
'SolarWorld','Industrials','Industrial machinery','Bonn',1988,'Photovoltaics',
'Sonor','Consumer goods','Recreational products','Berlin',1875,'Musical instruments',
'Sortimo','Industrials','Industrial suppliers','Zusmarshausen',1973,'In-vehicle equipment',
'Staedtler','Consumer goods','Nondurable household products','Nuremberg',1835,'Writing instruments',
'Steinway & Sons','Consumer goods','Recreational products','Hamburg',1853,'Musical instruments',
'Stihl','Basic materials','Forestry','Waiblingen',1926,'Forestry equipment, garden tools',
'Südzucker','Consumer goods','Food products','Mannheim',1926,'Sugar',
'Symrise','Personal products','Flavours, gustatory and cosmetic substances','Holzminden',2003,'Flavours, gustatory and cosmetic substances',
'Talanx','Financials','Full line insurance','Hanover',1996,'Commercial insurance',
'Tchibo','Consumer services','Broadline retailers','Hamburg',1949,'Consumer goods, retail',
'Telefunken','Consumer goods','Consumer electronics','Berlin',1903,'Defunct 1967',
'Tengelmann Group','Consumer services','Broadline retailers','Mülheim',1867,'Retail holding company',
'Tente International','Industrials','General industrials','Cologne',1923,'Wheels and castors',
'Tetra','Consumer services','Specialty retailers','Melle',1951,'Fishkeeping supplies',
'The Linde Group','Basic materials','Speciality chemicals','Munich',1879,'Industrial gas production and plant engineering',
'ThyssenKrupp','Conglomerates','-','Duisburg',1999,'Steel, engineering, shipyards',
'trivago','Technology','Internet','Düsseldorf',2005,'Hotel and travel search, part of Expedia, Inc. (US)',
'Trumpf','Industrials','Industrial machinery','Ditzingen',1923,'Machine tools',
'T-Systems','Technology','Software','Frankfurt',2000,'Part of Deutsche Telekom',
'TUI Group','Consumer services','Travel & leisure','Hanover',1923,'Hospitality, tourism',
'Ulla Popken','Consumer goods','Clothing & accessories','Rastede',1880,'Clothing',
'Ultrasone','Consumer goods','Consumer electronics','Tutzing',1991,'Audio electronics',
'Underberg','Consumer goods','Brewers','Rheinberg',1846,'Bitters',
'United Internet','Telecommunications','Fixed line telecommunications','Montabaur',1988,'ISP',
'Vaude','Consumer goods','Recreational products','Tettnang',1974,'Clothing, mountain sports equipment',
'Vector Informatik','Technology','Software','Stuttgart',1988,'Software',
'Vereinigte Flugtechnische Werke','Industrials','Aerospace','Bremen',1964,'Defunct 1981',
'Viessmann','Industrials','General industrials','Allendorf (Eder)',1917,'Heating systems',
'Villeroy & Boch','Consumer goods','Durable household products','Mettlach',1748,'Ceramics',
'Voith','Industrials','Industrial engineering','Heidenheim an der Brenz',1867,'Mechanical engineering',
'Volkswagen Group','Consumer goods','Automobiles','Wolfsburg',1937,'Automotive',
'Volkswagen','Consumer goods','Automobiles','Wolfsburg',1937,'Part of Volkswagen Group',
'Vonovia','Financials','Real estate','Bochum',2001,'Real estate',
'Vossloh','Industrials','Industrial transportation','Werdohl',1888,'Railway systems engineering',
'Wacker Chemie','Basic materials','Chemicals','Munich',1914,'Chemicals',
'Wacker Neuson','Industrials','Construction & materials','Munich',1848,'Construction equipment',
'WAGO Kontakttechnik','Industrials','Electrical components & equipment','Minden',1951,'Electrical components',
'Warsteiner','Consumer goods','Brewers','Warstein',1753,'Brewery',
'Wella','Consumer goods','Personal products','Darmstadt',1880,'Hair care and cosmetics',
'Wera Werk Hermann Werner','Consumer goods','Durable household products','Wuppertal',1936,'Tools',
'Weser Flugzeugbau','Industrials','Aerospace','Bremen',1934,'Defunct 1964',
'Wilkhahn','Consumer goods','Furnishings','Bad Münder',1907,'Office furniture',
'Wintershall','Oil & gas','Exploration & production','Kassel',1894,'Part of BASF',
'Wirecard','Financials','Financial services','Aschheim',1999,'Payment solutions',
'Wittenstein','Industrials','Industrial engineering','Igersheim',1949,'Mechanical engineering',
'Wolff & Müller','Industrials','Heavy construction','Stuttgart',1936,'Construction',
'Wortmann','Technology','Computer hardware','Hüllhorst',1986,'Computer manufacturer',
'Würth','Industrials','General industrials','Künzelsau',1945,'Fasteners',
'Wüsthof','Consumer goods','Durable household products','Solingen',1814,'Kitchen knives',
'ZF Friedrichshafen','Industrials','Industrial suppliers','Friedrichshafen',1915,'Automotive parts',
'Ziehl-Abegg SE','Industrials','Electrical components & equipment','Künzelsau',1910,'Electrical components'
]

# https://en.wikipedia.org/wiki/List_of_companies_of_Germany